name: Flask Docker CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Requirements
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Check Python Syntax
      - name: Run Python Check
        run: |
          python -m py_compile app.py

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t flask-notes-app .

      # Run Docker Container
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name flask-container flask-notes-app

      # Verify Running Containers
      - name: Check Running Containers
        run: docker ps
